server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
#Monitoring endpoints   
management:
   endpoints:
      web:
         exposure:
            include: info, health, configprops, logfile, metrics, env, loggers
logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE